<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>words100</RootNamespace>
    <AssemblyName>words100</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>false</EnableMsixTooling>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <DeployOnBuild>false</DeployOnBuild>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250402001" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\LargeTile310x310Logo.scale-200.png" />
    <Content Include="Assets\SmallTile71x71Logo.scale-200.png" />
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
    <Content Include="Assets\flagCZ.png" />
    <Content Include="Assets\flagEN.png" />
    <Content Include="Assets\flagFI.png" />
    <Content Include="Assets\flagPL.png" />
    <Content Include="Assets\dictionary.json" />
  </ItemGroup>
</Project>
